version: '3.7'

services:
  db:
    image: postgres:14.1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wy7Mt7zaJgq6ITy3
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5445:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: